# From: https://github.com/marketplace/actions/compile-arduino-sketches
# Uses: https://github.com/arduino/compile-sketches
name: Arduino Compile Sketches

on: 
  push:

jobs:
  compile-sketches: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Clone compile-sketches to get python version (using nektos/act locally)
        if: ${{ env.ACT }}
        run: cd /tmp; git clone 'https://github.com/arduino/compile-sketches'
      - name: setup-python (when running locally for nektos/act compatibility)
        if: ${{ env.ACT }}
        uses: actions/setup-python@v4
        with:
          python-version-file: /tmp/compile-sketches/.python-version
      - name: Install Poetry (when running locally for nektos/act compatibility)
        if: ${{ env.ACT }}
        uses: snok/install-poetry@v1
      - name: Install pipx (when running locally for nektos/act compatibility)
        if: ${{ env.ACT }}
        run: pip install pipx
      - name: Copy dummy secrets file.
        run: |
          cp MQTT_private_config-template.h MQTT_private_config.h
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: 'esp8266:esp8266:thing'
          platforms: |
            - name: 'esp8266:esp8266'
              version: latest
              source-url: 'http://arduino.esp8266.com/stable/package_esp8266com_index.json'
          sketch-paths: |
            - .
          verbose: true
          enable-warnings-report: true
          libraries: |
            - source-path: ./
            - name: OneWire
            - name: Adafruit MQTT Library



