# From: https://github.com/marketplace/actions/compile-arduino-sketches
# Uses: https://github.com/arduino/compile-sketches
name: Arduino Compile Sketches

on: 
  push:

jobs:
  compile-sketches: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Copy dummy secrets file.
        run: |
          cp MQTT_private_config-template.h MQTT_private_config.h
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: 'esp8266:esp8266:thing'
          platforms: |
            - name: 'esp8266:esp8266'
              version: latest
              source-url: 'http://arduino.esp8266.com/stable/package_esp8266com_index.json'
          sketch-paths: |
            - .
          verbose: true
          enable-warnings-report: true
          libraries: |
            - source-path: ./
            - name: OneWire
            - name: Adafruit MQTT Library



